services:
  app:
    build: ./app
    container_name: jobtracker_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./app/uploads:/var/www/html/uploads
    depends_on:
      - db # DB Starts first
  db:
    image: mysql:8
    container_name: jobtracker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
volumes:
  db_data: