services:
  app:
    build: ./app
    container_name: jobtracker_app
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./app/uploads:/var/www/html/uploads
    depends_on:
      - db # DB Starts first
  db:
    image: mysql
    container_name: jobtracker_db
    restart: always
    environment:
      - MYSQL_USER: ${MYSQL_USER}
      - MYSQL_PASS: ${MYSQL_PASS}
      - DB_NAME: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  
volumes:
  db_data: